### ISSUE TITLE
Feature Request : filter the endpoints being tracked

### ISSUE THREAD

**Issue by gtracy** [rosskukulinski/lynx-express#5]
It's all or nothing right now and that creates downstream challenges (processing + $$). It would be great to be able to specify the paths to instrument or those _not_ to instrument.

**Comment by rosskukulinski** [comment]
Hi @gtracy - I'm not really currently maintaining this project, but happy to accept a PR if you'd like to muck around in the code.

**Comment by gtracy** [comment]
Thanks. I wound up implementing it in the express-statsd package.
